name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  custom_radio_grouped_button: ^2.2.1
  customizable_counter: ^1.0.4
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_custom_clippers: ^2.1.0
  get: ^4.6.6
  http: ^1.2.0
  intl: ^0.19.0
  ionicons: ^0.2.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.10.0 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pics/logo.png"

flutter:
  assets:
    - assets/pics/
  uses-material-design: true
